[tool.poetry]
name = "mlstan"
version = "0.1.0"
description = "Venv for project ML"
authors = ["Pierre"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"
scikit-learn = "^1.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
